name: Enhanced Security Checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Semgrep Static Analysis
      - name: Semgrep Code Scan
        uses: semgrep/semgrep-action@v1
        with:
          config: >- 
            p/security-audit 
            p/xss 
            p/javascript 
            p/react

      # OWASP Dependency-Check
      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'GreenTech'
          path: '.'
          format: 'HTML'
          out: 'reports' 

      # Trivy Vulnerability Scanner
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      # Upload security scan results
      - name: Upload security scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'


  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'

      - name: Run npm audit
        working-directory: client
        run: |
          npm audit --audit-level=high
          npm audit signatures
