name: Jest Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  jest:
    name: Run Jest Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install
        working-directory: client

      - name: Run Jest tests
        run: npm test
        working-directory: client
