name: Google Lighthouse Performance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Lighthouse CI for Multiple Pages
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://dineth-lochana.github.io/GreenTechUOB/#/
            https://dineth-lochana.github.io/GreenTechUOB/#/Learn
            https://dineth-lochana.github.io/GreenTechUOB/#/fireSafety
            https://dineth-lochana.github.io/GreenTechUOB/#/variableDrives
            https://dineth-lochana.github.io/GreenTechUOB/#/projectShowcase
            https://dineth-lochana.github.io/GreenTechUOB/#/solar
            https://dineth-lochana.github.io/GreenTechUOB/#/SolarCalc
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Generate Lighthouse Report
        run: |
          echo "## Lighthouse Performance Report 🚀" > lighthouse-report.md
          echo "Last Updated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> lighthouse-report.md
          echo "" >> lighthouse-report.md
          
          # Add Links to Reports
          echo "### Page Performance Scores" >> lighthouse-report.md
          echo "- 🔗 [Homepage Report](https://dineth-lochana.github.io/GreenTechUOB/#/)" >> lighthouse-report.md
          echo "- 🔗 [learn Report](https://dineth-lochana.github.io/GreenTechUOB/#/Learn/)" >> lighthouse-report.md
          echo "- 🔗 [fireSafety Page Report](https://dineth-lochana.github.io/GreenTechUOB/#/fireSafety)" >> lighthouse-report.md
          echo "- 🔗 [variableDrives Page Report](https://dineth-lochana.github.io/GreenTechUOB/#/variableDrives)" >> lighthouse-report.md
          echo "- 🔗 [Project Showcase](https://dineth-lochana.github.io/GreenTechUOB/#/projectShowcase)" >> lighthouse-report.md
          echo "- 🔗 [Solar Energy Products Page](https://dineth-lochana.github.io/GreenTechUOB/#/solar)" >> lighthouse-report.md
          echo "- 🔗 [Solar ROI Calculatort](https://dineth-lochana.github.io/GreenTechUOB/#/SolarCalc)" >> lighthouse-report.md
          
          echo "\`\`\`" >> lighthouse-report.md
          echo "Performance, Accessibility, SEO, and Best Practices scores are available in detailed reports." >> lighthouse-report.md
          echo "\`\`\`" >> lighthouse-report.md

      - name: Update README with Lighthouse Report
        run: |
          if [ -f "README.md" ]; then
            sed -i '/## Lighthouse Performance Report/,$d' README.md
            cat lighthouse-report.md >> README.md
          else
            cp lighthouse-report.md README.md
          fi

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update Lighthouse performance report" || echo "No changes to commit"
          git push
