name: Google Lighthouse Performance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: "https://dineth-lochana.github.io/GreenTechUOB/#/"
          budgetPath: "./lighthouse-budget.json"
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Update README with Last Lighthouse Scan Date
        run: |
          TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
          echo "## 📊 Latest Performance Report" > lighthouse-report.md
          echo " **Last Updated:** $TIMESTAMP" >> lighthouse-report.md
          
          # Insert/Update in README.md
          if grep -q "## 📊 Latest Performance Report" README.md; then
            sed -i '/## 📊 Latest Performance Report/,$d' README.md
          fi
          cat lighthouse-report.md >> README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "📊 Update Lighthouse Performance Report - $TIMESTAMP" || echo "No changes to commit"
          git push
