name: Google Lighthouse Performance Test Dineth
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: write
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      
      - name: Pull Latest Changes
        run: |
          git pull origin master --rebase  # Using rebase since merge commits aren't allowed
      
      - name: Run Lighthouse CI for Multiple Pages
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://dineth-lochana.github.io/GreenTechUOB/#/variableDrives
          uploadArtifacts: false
          temporaryPublicStorage: true
      
      - name: Generate Lighthouse Report
        run: |
          echo "## Dineth Lighthouse test" > lighthouse-report.md
          echo "Last Updated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> lighthouse-report.md
          echo "" >> lighthouse-report.md
          
          echo "### Page Performance Scores" >> lighthouse-report.md
          echo "- 🔗 [Homepage Report](https://dineth-lochana.github.io/GreenTechUOB/#/)" >> lighthouse-report.md
          echo "- 🔗 [learn Report](https://dineth-lochana.github.io/GreenTechUOB/#/Learn/)" >> lighthouse-report.md
          echo "- 🔗 [fireSafety Page Report](https://dineth-lochana.github.io/GreenTechUOB/#/fireSafety)" >> lighthouse-report.md
          echo "- 🔗 [variableDrives Page Report](https://dineth-lochana.github.io/GreenTechUOB/#/variableDrives)" >> lighthouse-report.md
          
          echo "\`\`\`" >> lighthouse-report.md
          echo "Performance, Accessibility, SEO, and Best Practices scores are available in detailed reports." >> lighthouse-report.md
          echo "\`\`\`" >> lighthouse-report.md
      
      - name: Pull Latest Changes Again Before README Update
        run: |
          git pull origin master --rebase  # Pull again before updating README
      
      - name: Update README with Lighthouse Report
        run: |
          if [ -f "README.md" ]; then
            if grep -q "## Dineth Lighthouse test" README.md; then
              sed -i '/## Dineth Lighthouse test/,/## /{ /## Dineth Lighthouse test/!{ /## /!d; }; }' README.md
              sed -i '/## Dineth Lighthouse test/r lighthouse-report.md' README.md
              sed -i '/## Dineth Lighthouse test/d' README.md
            else
              cat lighthouse-report.md >> README.md
            fi
          else
            cp lighthouse-report.md README.md
          fi
      
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update Lighthouse performance report" || echo "No changes to commit"
          git pull origin master --rebase  # Pull one more time before pushing to ensure we have latest changes
          git push
