name: Lint and Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint-and-test:
    name: Run ESLint and Jest
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies
      - name: Install dependencies
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install
        working-directory: client

      # Run ESLint for code linting
      - name: Run ESLint
        run: npm run lint
        working-directory: client

      # Run Jest tests
      - name: Run Jest tests
        run: npm test
        working-directory: client
