name: CI and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    strategy:
      matrix:
        node-version: [23.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Clean install dependencies
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install
        working-directory: client

      - name: Install and build client
        working-directory: client
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}
          VITE_Chatling_API_KEY: ${{ secrets.VITE_Chatling_API_KEY }}
        run: |
          npm install
          npm run build

      - name: Zip build output
        run: zip -r build-output.zip client/dist
        shell: bash

      - name: Commit build zip
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add build-output.zip
          git commit -m "Add build output zip" || echo "No changes to commit" # Handle no changes case
          git push origin ${{ github.ref }}
        shell: bash

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'client/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
